# .github/workflows/email-on-push.yml
name: Email on Git Push

on:
  push:
    branches:
      -  # Trigger on all branches

jobs:
  email_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email via Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}    # your Gmail address
          password: ${{ secrets.EMAIL_PASSWORD }}    # Gmail App Password
          subject: "🚀 Commit on ${{ github.repository }} by ${{ github.actor }}"
          to: george.kithinji@strathmore.edu
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            A new commit was pushed to `${{ github.repository }}`.

            Branch: ${{ github.ref_name }}
            Author: ${{ github.actor }}
            Commit message: ${{ github.event.head_commit.message }}
            Commit URL: ${{ github.event.head_commit.url }}


